# Generated by Django 6.1 on 2026-09-22 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(verbose_name='Место проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('stage', models.IntegerField(verbose_name='Стадия')),
                ('progression', models.TextField(verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('stages_count', models.IntegerField(verbose_name='Количество стадий')),
                ('prize', models.TextField(verbose_name='Приз')),
                ('g_power_limit', models.IntegerField(verbose_name='Ограничение силы')),
                ('rules', models.TextField(verbose_name='Правила')),
            ],
        ),
        migrations.CreateModel(
            name='Participants_in_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(verbose_name='Название команды')),
                ('win_or_lose', models.BooleanField(verbose_name='Победа/поражение')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakugan_tournaments.games')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='tournament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakugan_tournaments.tournaments'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('approval', models.BooleanField(verbose_name='Одобрение')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakugan_tournaments.tournaments')),
            ],
        ),
    ]
