# Generated by Django 6.1 on 2026-09-22 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakugan_tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Participants_in_games',
            new_name='Participants_in_game',
        ),
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
    ]
