# Generated by Django 6.1 on 2026-09-23 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakugan_tournaments', '0002_rename_applications_application_rename_games_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
