# Generated by Django 6.1 on 2026-09-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakugan_tournaments', '0003_tournament_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='progression',
            new_name='status',
        ),
    ]
