# Generated by Django 6.1 on 2026-09-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakugan_tournaments', '0004_rename_progression_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='participants_in_game',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='participants_in_game',
            old_name='user_id',
            new_name='user',
        ),
    ]
